/**
 * Database utilities and Supabase client configuration
 */

import { createClient } from '@supabase/supabase-js'
import { Database } from './database.types'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables')
}

// Client-side Supabase client
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey)

// Server-side client with service role (for admin operations)
export function createServiceRoleClient() {
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  
  if (!serviceRoleKey) {
    throw new Error('Missing SUPABASE_SERVICE_ROLE_KEY environment variable')
  }
  
  return createClient<Database>(supabaseUrl, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  })
}

// Database utility functions
export async function insertAuditEvent(
  supabaseClient: typeof supabase,
  event: {
    user_id?: string
    entity: string
    entity_id?: string
    action: string
    payload?: Record<string, any>
  }
) {
  return await supabaseClient
    .from('audit_events')
    .insert(event)
}

// Helper function to get current user
export async function getCurrentUser(supabaseClient: typeof supabase) {
  const { data: { user }, error } = await supabaseClient.auth.getUser()
  if (error) {
    console.error('Error getting current user:', error)
    return null
  }
  return user
}

// Helper function to check if user is admin
export function isUserAdmin(user: any): boolean {
  if (!user) return false
  
  // Check JWT claims for admin role
  return user.user_metadata?.role === 'admin' || 
         user.app_metadata?.role === 'admin' ||
         user.app_metadata?.user_role === 'admin'
}

// Database types (to be generated by Supabase CLI)
export interface Database {
  public: {
    Tables: {
      manufacturers: {
        Row: {
          id: string
          name: string
          website: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          website?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          website?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      suppliers: {
        Row: {
          id: string
          name: string
          contact_name: string | null
          email: string | null
          phone: string | null
          website: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          website?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          website?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          customer_number: string
          name: string | null
          email: string | null
          phone: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          customer_number: string
          name?: string | null
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          customer_number?: string
          name?: string | null
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      status_codes: {
        Row: {
          code: number
          label: string
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          code: number
          label: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          code?: number
          label?: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      parts: {
        Row: {
          id: string
          c: string
          part: string
          desc: string | null
          vp1: number | null
          up1: string | null
          vp2: number | null
          up2: string | null
          sup: string | null
          mfg: string | null
          pn: string | null
          proj: string | null
          sec: string | null
          dwg: string | null
          id_from_dwg: string | null
          qty: number
          spare: number
          po: string | null
          re_sp: string | null
          ord: string | null
          wk: number | null
          s: number
          each: number | null
          d: string
          n: string | null
          l: string | null
          b: boolean
          w: string | null
          upd: string | null
          lc: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          c: string
          part: string
          desc?: string | null
          vp1?: number | null
          up1?: string | null
          vp2?: number | null
          up2?: string | null
          sup?: string | null
          mfg?: string | null
          pn?: string | null
          proj?: string | null
          sec?: string | null
          dwg?: string | null
          id_from_dwg?: string | null
          qty?: number
          spare?: number
          po?: string | null
          re_sp?: string | null
          ord?: string | null
          wk?: number | null
          s?: number
          each?: number | null
          d?: string
          n?: string | null
          l?: string | null
          b?: boolean
          w?: string | null
          upd?: string | null
          lc?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          c?: string
          part?: string
          desc?: string | null
          vp1?: number | null
          up1?: string | null
          vp2?: number | null
          up2?: string | null
          sup?: string | null
          mfg?: string | null
          pn?: string | null
          proj?: string | null
          sec?: string | null
          dwg?: string | null
          id_from_dwg?: string | null
          qty?: number
          spare?: number
          po?: string | null
          re_sp?: string | null
          ord?: string | null
          wk?: number | null
          s?: number
          each?: number | null
          d?: string
          n?: string | null
          l?: string | null
          b?: boolean
          w?: string | null
          upd?: string | null
          lc?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      purchase_orders: {
        Row: {
          id: string
          po_number: string
          supplier_id: string | null
          customer_id: string | null
          order_date: string | null
          notes: string | null
          currency: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          po_number: string
          supplier_id?: string | null
          customer_id?: string | null
          order_date?: string | null
          notes?: string | null
          currency?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          po_number?: string
          supplier_id?: string | null
          customer_id?: string | null
          order_date?: string | null
          notes?: string | null
          currency?: string
          created_at?: string
          updated_at?: string
        }
      }
      po_line_items: {
        Row: {
          id: string
          purchase_order_id: string
          part_id: string | null
          quantity: number
          unit_price: number | null
          currency: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          purchase_order_id: string
          part_id?: string | null
          quantity?: number
          unit_price?: number | null
          currency?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          purchase_order_id?: string
          part_id?: string | null
          quantity?: number
          unit_price?: number | null
          currency?: string
          created_at?: string
          updated_at?: string
        }
      }
      audit_events: {
        Row: {
          id: string
          user_id: string | null
          entity: string
          entity_id: string | null
          action: string
          payload: any | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          entity: string
          entity_id?: string | null
          action: string
          payload?: any | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          entity?: string
          entity_id?: string | null
          action?: string
          payload?: any | null
          created_at?: string
        }
      }
      raw_ingest: {
        Row: {
          id: string
          file_path: string
          uploader_user_id: string | null
          parsed_content: any | null
          ingest_report: any | null
          processing_status: string
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          file_path: string
          uploader_user_id?: string | null
          parsed_content?: any | null
          ingest_report?: any | null
          processing_status?: string
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          file_path?: string
          uploader_user_id?: string | null
          parsed_content?: any | null
          ingest_report?: any | null
          processing_status?: string
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      v_parts_readable: {
        Row: {
          id: string
          category_code: string
          category_name: string
          part: string
          description: string | null
          value_param_1: number | null
          units_1: string | null
          value_param_2: number | null
          units_2: string | null
          supplier_name: string | null
          supplier_id: string | null
          manufacturer_name: string | null
          manufacturer_id: string | null
          part_number: string | null
          project: string | null
          section: string | null
          drawing: string | null
          drawing_id: string | null
          quantity: number
          spare_quantity: number
          total_quantity: number
          purchase_order: string | null
          responsible_person: string | null
          order_date: string | null
          lead_time_weeks: number | null
          status_code: number
          status_label: string
          status_description: string | null
          unit_price: number | null
          currency_code: string
          currency_name: string
          line_total: number
          notes: string | null
          link: string | null
          is_budget_item: boolean
          last_updated_by: string | null
          last_update_date: string | null
          location_code: string | null
          location_name: string | null
          created_at: string
          updated_at: string
        }
      }
      v_po_summary: {
        Row: {
          id: string
          po_number: string
          order_date: string | null
          supplier_name: string | null
          customer_name: string | null
          customer_number: string | null
          currency: string
          line_item_count: number
          total_amount: number
          earliest_part_order_date: string | null
          latest_part_order_date: string | null
          unique_parts_count: number
          notes: string | null
          created_at: string
          updated_at: string
        }
      }
    }
    Functions: {
      rpc_search_parts: {
        Args: {
          search_po?: string
          search_customer?: string
          search_part?: string
          search_manufacturer?: string
          search_supplier?: string
          search_status?: number
          search_project?: string
          search_category?: string
          limit_count?: number
          offset_count?: number
        }
        Returns: {
          parts_data: any | null
          total_count: number
        }[]
      }
    }
  }
}
